# Generated by Django 4.2.30 on 2026-08-08 12:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('clube', '0002_galeria_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conquista',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('titulo', models.CharField(max_length=150, verbose_name='Título')),
                ('ano', models.PositiveIntegerField(verbose_name='Ano')),
                ('campeonato', models.CharField(max_length=150, verbose_name='Campeonato')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='conquistas/', verbose_name='Imagem')),
                ('destaque', models.BooleanField(default=False, verbose_name='Destaque')),
            ],
            options={
                'verbose_name': 'Conquista',
                'verbose_name_plural': 'Conquistas',
                'ordering': ['-ano'],
            },
        ),
        migrations.CreateModel(
            name='HallDaFama',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('nome', models.CharField(max_length=150, verbose_name='Nome')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='hall_da_fama/', verbose_name='Foto')),
                ('funcao', models.CharField(max_length=100, verbose_name='Função')),
                ('periodo', models.CharField(blank=True, max_length=100, verbose_name='Período')),
                ('biografia', models.TextField(blank=True, verbose_name='Biografia')),
                ('conquistas', models.TextField(blank=True, verbose_name='Principais Conquistas')),
                ('destaque', models.BooleanField(default=False, verbose_name='Destaque')),
            ],
            options={
                'verbose_name': 'Hall da Fama',
                'verbose_name_plural': 'Hall da Fama',
                'ordering': ['nome'],
            },
        ),
    ]
