# Generated by Django 4.2.30 on 2026-08-08 12:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('clube', '0003_conquista_halldafama'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patrocinador',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('nome', models.CharField(max_length=150, verbose_name='Nome')),
                ('logo', models.ImageField(upload_to='patrocinadores/', verbose_name='Logo')),
                ('site', models.URLField(blank=True, verbose_name='Site')),
                ('descricao', models.CharField(blank=True, max_length=255, verbose_name='Descrição')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('ativo_site', models.BooleanField(default=True, verbose_name='Exibir no site')),
            ],
            options={
                'verbose_name': 'Patrocinador',
                'verbose_name_plural': 'Patrocinadores',
                'ordering': ['ordem', 'nome'],
            },
        ),
    ]
